version: "3.1"

services:
  web:
    image: ${dockerid:-anoop}/counter-demo:${version:-latest}
    environment:
      ENVIRONMENT: ${env:-PRODUCTION}
    deploy:
      replicas: 10
#     labels:
#       com.docker.ucp.mesh.http: "external_route=http://applb-qxbxiw4ztbtve.eastus.cloudapp.azure.com,internal_port=8080"
    ports:
      - "8080"
    networks:
      - dubdub
#     - ucp-hrm

  db:
    image: redis:${redis-version:-latest}
    volumes:
      - data:/data
    networks:
      dubdub:

networks:
# ucp-hrm:
#   external: true
  dubdub:
    driver: overlay

volumes:
  data:
