version: "3.3"

services:
  web:
    image: ${dockerid:-anoop}/webserver:${webserver_version:-latest}
    environment:
      app_url: app:8080
    deploy:
      replicas: 1
    ports:
      - "2015:2015"
    networks:
      - frontend
 
  app:
    image: ${dockerid:-anoop}/counter-demo:${version:-onbuild}
    environment:
      ENVIRONMENT: ${env:-PRODUCTION}
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    networks:
      - frontend
      - backend

  db:
    image: redis:${redis_version:-latest}
    volumes:
      - data:/data
    networks:
      backend:

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

volumes:
  data:
