FROM golang:alpine
COPY src/demo.go /go/
RUN apk update && apk add git && \
# need git installed to run 'go get' on github
    go get github.com/garyburd/redigo/redis && \
# statically compile demo.go with all libraries built in
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

# The lines below are from part2 & are not necessary. 
# They are added merely to make this image (part1) useful to run by itself.
EXPOSE 8080
CMD ["/go/app"]
