version: "3.2"

services:
  web:
    image: ${dockerid:-anoop}/webserver:${webserver-version:-latest}
    environment:
      app_url: app:8080
    deploy:
      replicas: 5
#     labels:
#       com.docker.ucp.mesh.http: "external_route=http://app.noop.ga,internal_port=2015"
    ports:
      - "2015"
    networks:
      - frontend
#     - ucp-hrm
 
  app:
    image: ${dockerid:-anoop}/counter-demo:${version:-latest}
#   hostname: ${stackname:-app}-{{.Task.Slot}}
    environment:
      ENVIRONMENT: ${env:-PRODUCTION}
      DB_PASSWORD_FILE: /run/secrets/redis-pass
    deploy:
      replicas: 10
      endpoint_mode: dnsrr
    networks:
      - frontend
      - backend
    secrets:
      - redis-pass

  db:
    image: redis:${redis-version:-latest}
    command: ["redis-server", "/run/secrets/redis-pass"]
    secrets:
      - redis-pass
    volumes:
      - data:/data
    networks:
      backend:

secrets:
  redis-pass:
    external: true

networks:
# ucp-hrm:
#   external: true
  frontend:
    driver: overlay
  backend:
    driver: overlay

volumes:
  data:
