version: "3.2"

services:
  web:
    image: anoop/counter-demo:${version:-latest}
    environment:
      ENVIRONMENT: ${env:-PRODUCTION}
    deploy:
      replicas: 10
    ports:
      - "8080"
    networks:
      - dubdub

  db:
    image: redis:${redis-version:-latest}
    volumes:
      - data:/data
    networks:
      dubdub:

networks:
  dubdub:
    driver: overlay

volumes:
  data:
