apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noop-pv-claim
  namespace: noop
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

